### ISSUE TITLE
failed to find repeats

### ISSUE THREAD

**Issue by housw** [marbl/bambus3#4]
Hi, 

I got the following error while trying MetaCarvel, it looks like no repeats were found in the end, and raised an index error. Any idea? 

Thanks!
-Shengwei
```
Networkx 1.10 found
Fri Oct 12 10:40:44 2018:Starting scaffolding..
Fri Oct 12 10:40:51 2018:Finished conversion
Fri Oct 12 10:40:51 2018:Started generating links between contigs
Fri Oct 12 10:40:51 2018:Started bulding of links between contigs
Fri Oct 12 10:40:51 2018:Started finding and removing repeats
invalidating...ESP_78428
/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/home/shengwei/GitHub/Download/MetaCarvel/repeat_filter.py", line 65, in <module>
    p_degree = np.percentile(contig_degree.values(),75)
  File "/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3540, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3652, in _quantile_unchecked
    interpolation=interpolation)
  File "/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3250, in _ureduce
    r = func(a, **kwargs)
  File "/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3767, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 181, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/shengwei/anaconda3/envs/MetaCarvel/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
Fri Oct 12 10:40:53 2018: Failed to find repeats, terminating scaffolding....
```

**Comment by ghuryejay** [comment]
Hi,

Can you please post the output of `wc -l bundled_links`?

**Comment by housw** [comment]
yes, it has 0 line:
```
$ wc -l bundled_links
0 bundled_links
```
Thanks!

**Comment by housw** [comment]
just for your information, some of the files have 0 sizes: 
```
total   1.4G
drwxrwxr-x 2     4.0K     Oct 12 11:23 ./
drwxrwxr-x 6     4.0K     Oct 12 11:15 ../
-rw-rw-r-- 1       1.4G     Oct 12 11:22 alignment.bed
-rw-rw-r-- 1       405K     Oct 12 11:23 bundled_graph.gml
-rw-rw-r-- 1          0        Oct 12 11:23 bundled_links
-rw-rw-r-- 1          0        Oct 12 11:23 bundled_links_filtered
-rw-rw-r-- 1        120      Oct 12 11:23 contig_coverage
-rw-rw-r-- 1       2.4M     Oct 12 11:22 contig_length
-rw-rw-r-- 1       273K     Oct 12 11:23 contig_links
-rw-rw-r-- 1          0        Oct 12 11:23 high_centrality.txt
-rw-rw-r-- 1         12       Oct 12 11:23 invalidated_counts
-rw-rw-r-- 1        105      Oct 12 11:23 oriented.gml
-rw-rw-r-- 1          0        Oct 12 11:23 oriented_links
```

**Comment by ghuryejay** [comment]
Thanks. It's strange that the files are empty. 

Can you please post the output of `head -n 10 alignment.bed`?

**Comment by housw** [comment]
sure, 

```
$ head -n 10 alignment.bed 
ESP_78588	11815	11972	HWI-D00433:624:HN5JKBCXY:2:1101:1498:85681	1	+
ESP_78588	11821	11971	HWI-D00433:624:HN5JKBCXY:2:1101:1498:85681	1	-
ESP_124585	11927	12071	HWI-D00433:624:HN5JKBCXY:2:1101:1498:90912	21	+
ESP_26373	68	223	HWI-D00433:624:HN5JKBCXY:2:1101:1499:54487	6	-
ESP_26373	69	209	HWI-D00433:624:HN5JKBCXY:2:1101:1499:54487	6	+
ESP_26037	3523	3674	HWI-D00433:624:HN5JKBCXY:2:1101:1499:66467	42	+
ESP_45294	12590	12696	HWI-D00433:624:HN5JKBCXY:2:1101:1499:73972	8	+
ESP_55640	98	290	HWI-D00433:624:HN5JKBCXY:2:1101:1499:77308	25	+
ESP_55640	98	289	HWI-D00433:624:HN5JKBCXY:2:1101:1499:77308	14	-
ESP_140312	1544	1716	HWI-D00433:624:HN5JKBCXY:2:1101:1499:91605	42	-
```

**Comment by housw** [comment]
and the link file also looks fine:
```
$ head contig_links
ESP_104092	E	ESP_50764	B	-2682.33	57.2732
ESP_78799	B	ESP_25282	E	-71195.3	57.2732
ESP_125210	B	ESP_19309	B	-2468.33	57.2732
ESP_59525	E	ESP_44695	B	-19243.3	57.2732
ESP_114971	B	ESP_96812	B	-59838.3	57.2732
ESP_25325	B	ESP_7776	B	-73041.3	57.2732
ESP_36897	B	ESP_130938	B	-7631.33	57.2732
ESP_44576	E	ESP_7890	B	-6748.33	57.2732
ESP_78709	E	ESP_128960	E	-15007.3	57.2732
ESP_25	B	ESP_89452	B	-10662.3	57.2732
```

**Comment by ghuryejay** [comment]
Can you pull the latest code? After you do, please run `make clean` and then `make` to rebuild the c++ code (No need to rebuild OGDF). After you rebuild it, please run `run.py` the way you were running before and check if you get the same error.

**Comment by housw** [comment]
Hi Jay, 

thanks a lot for your quick fix, it's writing the mgsc database now!

Cheers, 
Shengwei
